// Composio-style toolkit catalog (MCP connectors)
// Reference: https://github.com/ComposioHQ/composio
export type AuthType = "oauth2" | "api_key" | "bearer" | "basic" | "no_auth";

export interface Toolkit {
  slug: string;
  name: string;
  category: string;
  auth: AuthType;
  desc: string;
  actions: number;
}

const t = (slug: string, name: string, category: string, auth: AuthType, desc: string, actions: number): Toolkit =>
  ({ slug, name, category, auth, desc, actions });

export const TOOLKITS: Toolkit[] = [
  t("gmail", "Gmail", "Productivity", "oauth2", "Send, read and label email threads", 28),
  t("googlecalendar", "Google Calendar", "Productivity", "oauth2", "Create and manage calendar events", 19),
  t("googledrive", "Google Drive", "Storage", "oauth2", "Upload, search and share files", 22),
  t("googledocs", "Google Docs", "Productivity", "oauth2", "Create and edit documents", 16),
  t("googlesheets", "Google Sheets", "Data", "oauth2", "Read and write spreadsheet rows", 21),
  t("googlemeet", "Google Meet", "Communication", "oauth2", "Create meetings and fetch recordings", 7),
  t("slack", "Slack", "Communication", "oauth2", "Post messages, manage channels and users", 34),
  t("discord", "Discord", "Communication", "oauth2", "Send messages and manage guilds", 24),
  t("microsoft_teams", "Microsoft Teams", "Communication", "oauth2", "Chats, channels and meetings", 18),
  t("outlook", "Outlook", "Productivity", "oauth2", "Mail, calendar and contacts", 26),
  t("onedrive", "OneDrive", "Storage", "oauth2", "Files and folders on Microsoft 365", 14),
  t("notion", "Notion", "Productivity", "oauth2", "Pages, databases and blocks", 23),
  t("linear", "Linear", "Project Mgmt", "oauth2", "Issues, projects and cycles", 20),
  t("jira", "Jira", "Project Mgmt", "oauth2", "Issues, sprints and boards", 31),
  t("confluence", "Confluence", "Productivity", "oauth2", "Spaces and pages", 15),
  t("asana", "Asana", "Project Mgmt", "oauth2", "Tasks, projects and portfolios", 25),
  t("trello", "Trello", "Project Mgmt", "api_key", "Boards, lists and cards", 22),
  t("clickup", "ClickUp", "Project Mgmt", "oauth2", "Tasks, docs and goals", 27),
  t("monday", "monday.com", "Project Mgmt", "oauth2", "Boards and items", 17),
  t("github", "GitHub", "Developer", "oauth2", "Repos, issues, PRs and actions", 48),
  t("gitlab", "GitLab", "Developer", "oauth2", "Projects, merge requests and pipelines", 29),
  t("bitbucket", "Bitbucket", "Developer", "oauth2", "Repositories and pull requests", 18),
  t("sentry", "Sentry", "Developer", "oauth2", "Issues, releases and alerts", 16),
  t("vercel", "Vercel", "Developer", "bearer", "Deployments, projects and domains", 20),
  t("netlify", "Netlify", "Developer", "bearer", "Sites, builds and deploys", 14),
  t("supabase", "Supabase", "Developer", "api_key", "Database, storage and auth admin", 19),
  t("firebase", "Firebase", "Developer", "api_key", "Firestore and cloud messaging", 15),
  t("aws_s3", "AWS S3", "Storage", "basic", "Buckets and object operations", 12),
  t("cloudflare", "Cloudflare", "Developer", "bearer", "DNS, workers and cache", 21),
  t("docker", "Docker Hub", "Developer", "api_key", "Repositories and tags", 9),
  t("hubspot", "HubSpot", "CRM", "oauth2", "Contacts, deals and companies", 38),
  t("salesforce", "Salesforce", "CRM", "oauth2", "Leads, opportunities and accounts", 42),
  t("pipedrive", "Pipedrive", "CRM", "oauth2", "Deals, persons and activities", 24),
  t("zoho_crm", "Zoho CRM", "CRM", "oauth2", "Modules, records and workflows", 26),
  t("attio", "Attio", "CRM", "api_key", "Records, lists and notes", 13),
  t("intercom", "Intercom", "Support", "oauth2", "Conversations and contacts", 20),
  t("zendesk", "Zendesk", "Support", "oauth2", "Tickets, users and macros", 28),
  t("freshdesk", "Freshdesk", "Support", "api_key", "Tickets and agents", 17),
  t("crisp", "Crisp", "Support", "api_key", "Conversations and people", 11),
  t("front", "Front", "Support", "oauth2", "Inboxes and conversations", 15),
  t("stripe", "Stripe", "Payments", "api_key", "Customers, invoices and subscriptions", 35),
  t("paypal", "PayPal", "Payments", "oauth2", "Payments and payouts", 16),
  t("quickbooks", "QuickBooks", "Finance", "oauth2", "Invoices, customers and reports", 24),
  t("xero", "Xero", "Finance", "oauth2", "Invoices, contacts and accounts", 22),
  t("brex", "Brex", "Finance", "bearer", "Cards, budgets and transactions", 12),
  t("ramp", "Ramp", "Finance", "oauth2", "Spend, cards and reimbursements", 14),
  t("mailchimp", "Mailchimp", "Marketing", "oauth2", "Audiences and campaigns", 21),
  t("sendgrid", "SendGrid", "Marketing", "api_key", "Transactional email and templates", 18),
  t("klaviyo", "Klaviyo", "Marketing", "api_key", "Profiles, lists and flows", 19),
  t("customerio", "Customer.io", "Marketing", "api_key", "People, events and campaigns", 15),
  t("activecampaign", "ActiveCampaign", "Marketing", "api_key", "Contacts and automations", 17),
  t("twitter", "X (Twitter)", "Social", "oauth2", "Post, search and analytics", 23),
  t("linkedin", "LinkedIn", "Social", "oauth2", "Share posts and company pages", 14),
  t("facebook", "Facebook Pages", "Social", "oauth2", "Posts, insights and comments", 19),
  t("instagram", "Instagram", "Social", "oauth2", "Media, insights and comments", 16),
  t("reddit", "Reddit", "Social", "oauth2", "Posts, comments and subreddits", 18),
  t("youtube", "YouTube", "Social", "oauth2", "Videos, playlists and analytics", 22),
  t("tiktok", "TikTok", "Social", "oauth2", "Videos and account insights", 12),
  t("buffer", "Buffer", "Social", "oauth2", "Schedule and queue posts", 10),
  t("hootsuite", "Hootsuite", "Social", "oauth2", "Streams and scheduled posts", 11),
  t("typefully", "Typefully", "Social", "api_key", "Draft and schedule threads", 8),
  t("airtable", "Airtable", "Data", "oauth2", "Bases, tables and records", 20),
  t("snowflake", "Snowflake", "Data", "basic", "Warehouses and SQL queries", 12),
  t("bigquery", "BigQuery", "Data", "oauth2", "Datasets and query jobs", 14),
  t("postgres", "PostgreSQL", "Data", "basic", "Run queries and inspect schema", 9),
  t("mongodb", "MongoDB", "Data", "basic", "Collections and documents", 13),
  t("posthog", "PostHog", "Analytics", "api_key", "Events, insights and flags", 18),
  t("mixpanel", "Mixpanel", "Analytics", "api_key", "Events, funnels and cohorts", 15),
  t("amplitude", "Amplitude", "Analytics", "api_key", "Events and charts", 13),
  t("googleanalytics", "Google Analytics", "Analytics", "oauth2", "Reports and realtime metrics", 16),
  t("semrush", "Semrush", "Analytics", "api_key", "Keywords, domains and backlinks", 17),
  t("ahrefs", "Ahrefs", "Analytics", "api_key", "Backlinks and keyword data", 14),
  t("googlesearchconsole", "Search Console", "Analytics", "oauth2", "Search performance and indexing", 11),
  t("figma", "Figma", "Design", "oauth2", "Files, comments and components", 15),
  t("canva", "Canva", "Design", "oauth2", "Designs, brand kits and exports", 12),
  t("miro", "Miro", "Design", "oauth2", "Boards and widgets", 14),
  t("dropbox", "Dropbox", "Storage", "oauth2", "Files, folders and sharing", 18),
  t("box", "Box", "Storage", "oauth2", "Files, folders and collaborations", 16),
  t("calendly", "Calendly", "Scheduling", "oauth2", "Event types and invitees", 12),
  t("cal_com", "Cal.com", "Scheduling", "api_key", "Bookings and availability", 11),
  t("zoom", "Zoom", "Communication", "oauth2", "Meetings, webinars and recordings", 24),
  t("twilio", "Twilio", "Communication", "basic", "SMS, voice and verify", 20),
  t("whatsapp", "WhatsApp Business", "Communication", "bearer", "Messages and templates", 13),
  t("telegram", "Telegram", "Communication", "bearer", "Bot messages and chats", 15),
  t("shopify", "Shopify", "E-commerce", "oauth2", "Products, orders and customers", 32),
  t("woocommerce", "WooCommerce", "E-commerce", "basic", "Products and orders", 21),
  t("bigcommerce", "BigCommerce", "E-commerce", "api_key", "Catalog and orders", 18),
  t("amazon_seller", "Amazon Seller", "E-commerce", "oauth2", "Listings, orders and reports", 19),
  t("docusign", "DocuSign", "Documents", "oauth2", "Envelopes and signatures", 17),
  t("pandadoc", "PandaDoc", "Documents", "api_key", "Documents and templates", 13),
  t("dropbox_sign", "Dropbox Sign", "Documents", "api_key", "Signature requests", 10),
  t("openai", "OpenAI", "AI", "api_key", "Chat, embeddings and images", 12),
  t("anthropic", "Anthropic", "AI", "api_key", "Claude messages and tools", 8),
  t("perplexity", "Perplexity", "AI", "api_key", "Grounded answers with citations", 6),
  t("elevenlabs", "ElevenLabs", "AI", "api_key", "Text to speech and voices", 10),
  t("firecrawl", "Firecrawl", "AI", "api_key", "Crawl and scrape web pages", 7),
  t("exa", "Exa", "AI", "api_key", "Neural web search", 6),
  t("tavily", "Tavily", "AI", "api_key", "Search and extract for agents", 5),
  t("serpapi", "SerpApi", "AI", "api_key", "Search engine results", 8),
  t("apollo", "Apollo.io", "Sales", "api_key", "Prospects, sequences and enrichment", 19),
  t("outreach", "Outreach", "Sales", "oauth2", "Sequences, prospects and calls", 22),
  t("salesloft", "SalesLoft", "Sales", "oauth2", "Cadences and people", 18),
  t("lemlist", "Lemlist", "Sales", "api_key", "Campaigns and leads", 12),
  t("clearbit", "Clearbit", "Sales", "api_key", "Company and person enrichment", 8),
  t("dropcontact", "Dropcontact", "Sales", "api_key", "Email enrichment and validation", 6),
  t("greenhouse", "Greenhouse", "HR", "basic", "Jobs, candidates and scorecards", 20),
  t("lever", "Lever", "HR", "api_key", "Postings and opportunities", 16),
  t("bamboohr", "BambooHR", "HR", "api_key", "Employees and time off", 14),
  t("workday", "Workday", "HR", "oauth2", "Workers and org data", 18),
  t("gusto", "Gusto", "HR", "oauth2", "Payroll and employees", 13),
  t("prnewswire", "PR Newswire", "PR & Media", "api_key", "Distribute press releases", 7),
  t("businesswire", "Business Wire", "PR & Media", "api_key", "Release distribution and reports", 6),
  t("muckrack", "Muck Rack", "PR & Media", "api_key", "Journalists, outlets and coverage", 11),
  t("cision", "Cision", "PR & Media", "api_key", "Media database and monitoring", 13),
  t("meltwater", "Meltwater", "PR & Media", "api_key", "Media monitoring and analytics", 12),
  t("newsapi", "NewsAPI", "PR & Media", "api_key", "Headlines and article search", 5),
  t("googlenews", "Google News", "PR & Media", "no_auth", "Search news headlines", 4),
  t("rss", "RSS Feeds", "PR & Media", "no_auth", "Read and parse feeds", 3),
  t("webhook", "Webhook", "Utilities", "no_auth", "Send HTTP requests to any URL", 4),
  t("gcal_watch", "Cron / Scheduler", "Utilities", "no_auth", "Trigger tools on a schedule", 3),
  t("code_interpreter", "Code Interpreter", "Utilities", "no_auth", "Run sandboxed Python", 5),
  t("text_to_pdf", "File Tools", "Utilities", "no_auth", "Convert, split and merge files", 9),
];

export const CATEGORIES = Array.from(new Set(TOOLKITS.map((k) => k.category))).sort();

export const AUTH_LABEL: Record<AuthType, string> = {
  oauth2: "OAuth 2.0",
  api_key: "API Key",
  bearer: "Bearer Token",
  basic: "Username / Password",
  no_auth: "No Auth",
};

export const getToolkit = (slug: string) => TOOLKITS.find((k) => k.slug === slug);
